# Generated by Django 2.2 on 2021-05-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Xueqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xueqi', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('A', models.CharField(max_length=50)),
                ('B', models.CharField(max_length=50)),
                ('C', models.CharField(max_length=50)),
                ('D', models.CharField(max_length=50)),
                ('correct', models.CharField(max_length=5)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Calss')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('g_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Mistakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Student')),
                ('ti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Timu')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='t_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Teacher'),
        ),
        migrations.CreateModel(
            name='Chengji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheng', models.IntegerField(null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Calss')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Student')),
                ('x_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Xueqi')),
            ],
        ),
    ]
