# Generated by Django 2.2 on 2021-05-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210418_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chengji',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Calss'),
        ),
        migrations.AlterField(
            model_name='chengji',
            name='x_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Xueqi'),
        ),
        migrations.CreateModel(
            name='Timu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('A', models.CharField(max_length=50)),
                ('B', models.CharField(max_length=50)),
                ('C', models.CharField(max_length=50)),
                ('D', models.CharField(max_length=50)),
                ('correct', models.CharField(max_length=5)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Calss')),
            ],
        ),
        migrations.CreateModel(
            name='Mistakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Student')),
                ('ti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Timu')),
            ],
        ),
    ]
